version: "3.0"
services:
    api:
        build: docker/api
        volumes:
            - ./api:/api
        ports:
            - "127.0.0.1:8080:80"
        depends_on:
            - database

    database:
        image: docker.io/mysql:9.0.1
        volumes:
            - ./docker/_vol/database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=pmt
            - MYSQL_USER=pmt
            - MYSQL_PASSWORD=pmt
        ports:
            - "127.0.0.1:3306:3306"

    angular_app:
        container_name: angular_app
        build:
            context: ./angular_app
            dockerfile: Dockerfile

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        expose:
            - "80"
        ports:
            - "80:80"
        volumes:
            - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
        depends_on:
            - api